// Copyright (c) 2020 Microsoft Corporation.
// Licensed under the MIT License.

// This file is autogenerated - do not commit manual changes.

#pragma once

#define UXTOOLSEXAMPLES_COMMIT_SHA "ffecd4026d52a06d5296c17fa4731d45e6c7d0a7"
